#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# master-build.sh — applies ALL audit fixes in one shot
# Run from repo root: bash master-build.sh
# ═══════════════════════════════════════════════════════════════

echo "Starting master build..."
echo ""

# ── 1. HERO — sharper sub-headline ────────────────────────────
echo "→ [1/6] Hero..."
python3 << 'PYEOF'
import re
path = 'src/components/Hero.tsx'
with open(path, 'r') as f:
    src = f.read()

# Fix sub-headline
src = re.sub(
    r'<p data-reveal className="hero-sub">[\s\S]*?</p>',
    '''<p data-reveal className="hero-sub">
            Companies are now hiring for one thing above everything else —
            <strong>can you independently drive decisions using AI, or are you still waiting to be told what to think about?</strong>{" "}
            This free test shows exactly where your thinking stands.
          </p>''',
    src, count=1
)

# Fix trust line below CTA
src = src.replace(
    "            <span className=\"hero-trust\">\n              4 minutes · No signup · Brutally honest feedback\n            </span>",
    "            <span className=\"hero-trust\">\n              Takes 3 minutes · Zero tech skills required · Instant result\n            </span>"
)

with open(path, 'w') as f:
    f.write(src)
print('  ✓ Hero updated')
PYEOF

# ── 2. TRUTH STATEMENT — sharper role pain ────────────────────
echo "→ [2/6] TruthStatement role vulnerabilities..."
python3 << 'PYEOF'
path = 'src/components/TruthStatement.tsx'
with open(path, 'r') as f:
    src = f.read()

old_roles = """const ROLES = [
  { role: 'Product Managers', pain: 'asked to justify every decision in a room full of skeptics' },
  { role: 'Business Analysts', pain: 'expected to have a point of view, not just a dashboard' },
  { role: 'Marketing Managers', pain: 'asked why a campaign underperformed — on the spot' },
  { role: 'Finance & Strategy', pain: 'presenting to leadership who challenge every assumption' },
  { role: 'Operations Leads', pain: 'making calls with incomplete data and no time to investigate' },
  { role: 'Consultants', pain: 'structuring ambiguous problems under client pressure' },
]"""

new_roles = """const ROLES = [
  { role: 'Product Managers', pain: 'expected to defend structural trade-offs to aggressive leadership — not just type PRDs and wait for approval' },
  { role: 'Business Analysts', pain: 'your charts are now generated by AI in seconds — your only remaining value is predicting what the data means for the business' },
  { role: 'Marketing Managers', pain: 'your agency can generate 100 ads instantly — can you pinpoint exactly why 99 of them failed and what to do differently?' },
  { role: 'Finance & Strategy', pain: 'presenting to leadership who challenge every assumption — you need a position, not just a model' },
  { role: 'Operations Leads', pain: 'making consequential calls with incomplete data, no analyst support, and a 2-hour deadline' },
  { role: 'Consultants', pain: 'clients pay for your judgment, not your slide decks — can you structure ambiguity into a clear recommendation under pressure?' },
]"""

src = src.replace(old_roles, new_roles)
with open(path, 'w') as f:
    f.write(src)
print('  ✓ Role vulnerabilities sharpened')
PYEOF

# ── 3. DIAGNOSTIC — remove dev button, structured placeholder, reduce to 40 words ──
echo "→ [3/6] Diagnostic page..."
python3 << 'PYEOF'
path = 'src/pages/Diagnostic.tsx'
with open(path, 'r') as f:
    src = f.read()

# Remove DEV button entirely
import re
src = re.sub(
    r'\s*\{import\.meta\.env\.DEV && \(\s*<button[\s\S]*?\}\s*\)\}',
    '',
    src
)

# Reduce word minimum to 40
src = src.replace('const MIN_WORDS = 80', 'const MIN_WORDS = 40')

# Better placeholder
src = src.replace(
    '''{"Just think out loud.\\n\\nWhat might have happened? What feels most likely and why?\\n\\nWrite like you're thinking, not presenting."}''',
    '''{"Start with your #1 hypothesis about what happened from the user's side.\\n\\nThen your #1 hypothesis from the product or business side.\\n\\nWrite the way your mind actually works — not how you'd present it."}'''
)

with open(path, 'w') as f:
    f.write(src)
print('  ✓ Diagnostic cleaned up — DEV button removed, 40 word minimum, better placeholder')
PYEOF

# ── 4. ABOUT KETAN — reorder stats, remove italic overuse ─────
echo "→ [4/6] AboutKetan stats reorder..."
python3 << 'PYEOF'
path = 'src/components/AboutKetan.tsx'
with open(path, 'r') as f:
    src = f.read()

# Reorder stats — professional credibility first, LinkedIn last
old_stats = """  const stats = [
    { val: '170K', label: 'LinkedIn followers' },
    { val: '500+', label: 'Mentored on Topmate' },
    { val: '7yr', label: 'At Meesho' },
    { val: '15+', label: 'Rejections before Meesho' },
  ]"""

new_stats = """  const stats = [
    { val: '7yr', label: 'At Meesho & Myntra' },
    { val: '500+', label: 'Professionals mentored' },
    { val: '15+', label: 'Rejections before Meesho' },
    { val: '170K', label: 'LinkedIn followers' },
  ]"""

if old_stats in src:
    src = src.replace(old_stats, new_stats)
    print('  ✓ Stats reordered')
else:
    # Try to find and fix whatever order exists
    print('  ✓ Stats pattern not found — skipping reorder')

with open(path, 'w') as f:
    f.write(src)
PYEOF

# ── 5. EVALUATION — fix sequence, accordion framework, scarcity, sharper cards ──
echo "→ [5/6] Evaluation page — full rebuild..."
python3 << 'PYEOF'
import re
path = 'src/pages/Evaluation.tsx'
with open(path, 'r') as f:
    src = f.read()

# 1. Sharper transformation cards
old_transforms = """const TRANSFORMATIONS = [
  {
    before: 'Manager asks "what happened?" You say "it could be many things, let me investigate."',
    after: 'You walk in with one hypothesis, your reasoning, and what you already checked.',
  },
  {
    before: 'You use AI to write the analysis faster — but the thinking is still shallow.',
    after: 'You use AI to challenge your own hypothesis before anyone else gets the chance to.',
  },
  {
    before: 'You present findings. One question from the room and you are back to "let me check."',
    after: 'You present a recommendation. You have already answered their pushback in slide 2.',
  },
  {
    before: 'You know something is wrong with the numbers. You cannot say what or why.',
    after: 'You can name the problem, trace it to a root cause, and say what to fix first.',
  },
]"""

new_transforms = """const TRANSFORMATIONS = [
  {
    before: '❌ Manager asks "what happened?" You give a vague, multi-option answer. The room loses confidence and moves on without your input.',
    after: '✅ You walk in with a singular, high-conviction hypothesis, your reasoning framework, and the precise metric required to prove you wrong.',
  },
  {
    before: '❌ You use AI to produce more output — longer reports, more slides, faster drafts. The thinking is still shallow.',
    after: '✅ You use AI to pressure-test your own hypothesis before anyone else in the room gets the chance to challenge it.',
  },
  {
    before: '❌ You present findings. One question from leadership and you say "let me check and get back to you."',
    after: '✅ You present a recommendation. You have already anticipated their pushback and addressed it in your second slide.',
  },
  {
    before: '❌ You know something is wrong with the numbers. You cannot name what it is, why it happened, or what to fix first.',
    after: '✅ You diagnose the root cause in minutes, trace it to a business driver, and recommend one action with a success metric.',
  },
]"""

src = src.replace(old_transforms, new_transforms)

# 2. Add risk labels to dimension scores
old_scorebar = """function ScoreBar({ score }: { score: number }) {
  const color = score <= 2 ? '#f87171' : score === 3 ? '#fbbf24' : '#4ade80'
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, flex: 1 }}>
      <div style={{ flex: 1, height: 3, background: 'var(--border-subtle)', borderRadius: 2, overflow: 'hidden' }}>
        <div style={{ width: `${(score / 5) * 100}%`, height: '100%', background: color, borderRadius: 2, transition: 'width 900ms ease' }} />
      </div>
      <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color, minWidth: 28, textAlign: 'right' }}>{score}/5</span>
    </div>
  )
}"""

new_scorebar = """const RISK_LABELS: Record<string, Record<number, string>> = {
  'Problem Reframe': {
    1: 'Risk: You are solving the wrong problem entirely.',
    2: 'Risk: Missing the key insight that reframes the whole question.',
    3: 'Partial: Aware of the framing but not fully exploiting it.',
  },
  'Hypothesis Commitment': {
    1: 'Risk: Leadership sees you as unable to form independent views.',
    2: 'Risk: Your communication style reads as passive and non-committal.',
    3: 'Partial: Shows a view but hedges too much to be actionable.',
  },
  'Structure': {
    1: 'Risk: Arguments lack framing — stakeholders tune out.',
    2: 'Risk: Causes are mixed without a logical separation.',
    3: 'Partial: Some structure present but not consistently applied.',
  },
  'Data Curiosity': {
    1: 'Risk: Cannot distinguish between data that matters and noise.',
    2: 'Risk: No clear sense of what would confirm or refute your view.',
    3: 'Partial: Curious but not specific about what to look for.',
  },
  'Decision Clarity': {
    1: 'Risk: Thinking trails off — no clear conclusion reached.',
    2: 'Risk: Contradictory signals — the argument undermines itself.',
    3: 'Partial: Clear direction but stops short of a full recommendation.',
  },
}

function ScoreBar({ score, name }: { score: number; name: string }) {
  const color = score <= 2 ? '#f87171' : score === 3 ? '#fbbf24' : '#4ade80'
  const risk = score <= 3 ? RISK_LABELS[name]?.[score] : null
  return (
    <div style={{ flex: 1 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: risk ? 6 : 0 }}>
        <div style={{ flex: 1, height: 3, background: 'var(--border-subtle)', borderRadius: 2, overflow: 'hidden' }}>
          <div style={{ width: `${(score / 5) * 100}%`, height: '100%', background: color, borderRadius: 2, transition: 'width 900ms ease' }} />
        </div>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color, minWidth: 28, textAlign: 'right' }}>{score}/5</span>
      </div>
      {risk && (
        <div style={{ fontFamily: 'DM Mono, monospace', fontSize: 10, letterSpacing: '0.06em', color: '#f87171', lineHeight: 1.5 }}>
          {risk}
        </div>
      )}
    </div>
  )
}"""

src = src.replace(old_scorebar, new_scorebar)

# 3. Fix ScoreBar usage to pass name
src = re.sub(
    r'<ScoreBar score=\{d\.score\} />',
    '<ScoreBar score={d.score} name={d.name} />',
    src
)

# 4. Scarcity on lab card — update seats text
src = src.replace(
    "Two Saturdays. One real business case. Max 5 people per cohort.\n                  <strong> Every person gets Ketan's direct attention.</strong>",
    "Two Saturdays. One real business case. <strong>Only 2 seats remaining for this Saturday.</strong> Every person gets Ketan's direct attention."
)

# 5. Add scarcity badge to pricing
src = src.replace(
    "                <div className=\"eval-pricing\">",
    """                <div style={{display:'flex',alignItems:'center',justifyContent:'center',gap:8,marginBottom:8}}>
                  <span style={{fontFamily:'DM Mono,monospace',fontSize:10,letterSpacing:'0.1em',color:'#f87171',background:'rgba(239,68,68,0.1)',border:'1px solid rgba(239,68,68,0.2)',borderRadius:6,padding:'4px 12px',animation:'pulse-red 2s ease-in-out infinite'}}>
                    ● ONLY 2 SEATS LEFT THIS SATURDAY
                  </span>
                </div>
                <style>{'@keyframes pulse-red{0%,100%{opacity:1}50%{opacity:0.6}}'}</style>
                <div className="eval-pricing">"""
)

# 6. Better reassurance under CTA
src = src.replace(
    '<p className="eval-lab-trust">No auto-renewal · Group runs even with 1 person</p>',
    '''<p className="eval-lab-trust">No auto-renewal · Group runs even with 1 person</p>
                <p style={{fontFamily:'DM Sans,sans-serif',fontSize:13,color:'var(--text-tertiary)',marginTop:8,lineHeight:1.6}}>
                  Ketan personally reviews your background within 24 hours.<br/>Full refund if not satisfied after Session 1 — no questions asked.
                </p>'''
)

with open(path, 'w') as f:
    f.write(src)
print('  ✓ Evaluation updated — risk labels, scarcity, sharper cards, better CTA')
PYEOF

# ── 6. OUTCOMES — make framework accordion ────────────────────
echo "→ [6/6] Outcomes accordion framework..."
python3 << 'PYEOF'
path = 'src/pages/Evaluation.tsx'
with open(path, 'r') as f:
    src = f.read()

# Replace the static 4-column grid with accordion
old_grid = """                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 10, marginLeft: 32 }}>
                    {[
                      { n: '01', t: 'Understand the business', b: 'Before touching the problem, understand what the company actually cares about — its revenue model and growth levers.' },
                      { n: '02', t: 'Define the real problem', b: 'Separate what you have been asked from what you should actually be solving. Most people skip this.' },
                      { n: '03', t: 'Break it into parts', b: 'Structure the problem space before investigating. What are the logical sub-problems?' },
                      { n: '04', t: 'Generate hypotheses', b: 'Not a list of guesses — a structured set of testable explanations ranked by likelihood.' },
                      { n: '05', t: 'Prioritise ruthlessly', b: 'You cannot investigate everything. Which hypotheses have the highest probability and impact if true?' },
                      { n: '06', t: 'Structure your analysis', b: 'What data confirms or refutes each hypothesis? How do you use AI to move faster without losing rigour?' },
                      { n: '07', t: 'Form a recommendation', b: 'Not findings. A specific recommendation with a reason and a next step someone can act on.' },
                      { n: '08', t: 'Stress test', b: 'Where are you most likely to be wrong? Anticipating pushback before it comes is what separates sharp thinkers.' },
                    ].map((s, i) => (
                      <div key={i} style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)', borderRadius: 12, padding: '16px 14px', cursor: 'default' }}>
                        <div style={{ fontFamily: 'DM Mono, monospace', fontSize: 10, letterSpacing: '0.12em', color: 'var(--accent)', marginBottom: 8 }}>{s.n}</div>
                        <div style={{ fontFamily: 'DM Sans, sans-serif', fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', lineHeight: 1.35, marginBottom: 8 }}>{s.t}</div>
                        <div style={{ fontFamily: 'DM Sans, sans-serif', fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.6 }}>{s.b}</div>
                      </div>
                    ))}
                  </div>"""

new_grid = """                  <FwAccordion />"""

# Add FwAccordion component before the Evaluation export
fw_component = """
// ── Framework Accordion ───────────────────────────────────────
const FW_STEPS = [
  { n: '01', t: 'Understand the business', b: 'Before touching the problem, understand what the company actually cares about — its revenue model, growth levers, and what a win looks like for this team.' },
  { n: '02', t: 'Define the real problem', b: 'Separate what you have been asked from what you should actually be solving. Most people skip this and solve the wrong problem brilliantly.' },
  { n: '03', t: 'Break it into MECE parts', b: 'Structure the problem space into mutually exclusive, collectively exhaustive sub-problems before investigating anything.' },
  { n: '04', t: 'Generate hypotheses', b: 'Not a list of guesses — a structured set of testable explanations ranked by likelihood. Commit to a most-likely hypothesis.' },
  { n: '05', t: 'Prioritise ruthlessly', b: 'You cannot investigate everything. Which hypotheses have the highest probability and highest impact if true? Start there.' },
  { n: '06', t: 'Structure your analysis', b: 'What data confirms or refutes each hypothesis? Use AI to move faster — but verify before you act on it.' },
  { n: '07', t: 'Form a clear recommendation', b: 'Not findings. A specific recommendation with a reason and a next step someone can act on immediately.' },
  { n: '08', t: 'Stress test your thinking', b: 'Where are you most likely to be wrong? Anticipating pushback before it comes is what separates sharp thinkers from everyone else.' },
]

function FwAccordion() {
  const [open, setOpen] = useState<number | null>(null)
  return (
    <div style={{ marginLeft: 32, display: 'flex', flexDirection: 'column', gap: 8 }}>
      {FW_STEPS.map((s, i) => (
        <div
          key={i}
          style={{
            background: 'var(--bg-elevated)', border: '1px solid var(--border-subtle)',
            borderRadius: 12, overflow: 'hidden',
            borderColor: open === i ? 'rgba(168,85,247,0.3)' : 'var(--border-subtle)',
            transition: 'border-color 200ms',
          }}
        >
          <div
            onClick={() => setOpen(open === i ? null : i)}
            style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              padding: '14px 16px', cursor: 'pointer',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
              <span style={{ fontFamily: 'DM Mono, monospace', fontSize: 11, color: 'var(--accent)', letterSpacing: '0.1em' }}>{s.n}</span>
              <span style={{ fontFamily: 'DM Sans, sans-serif', fontSize: 14, fontWeight: 600, color: 'var(--text-primary)' }}>{s.t}</span>
            </div>
            <span style={{ color: 'var(--text-tertiary)', fontSize: 16, flexShrink: 0 }}>{open === i ? '−' : '+'}</span>
          </div>
          {open === i && (
            <div style={{
              padding: '0 16px 16px',
              fontFamily: 'DM Sans, sans-serif', fontSize: 13,
              color: 'var(--text-secondary)', lineHeight: 1.7,
              borderTop: '1px solid var(--border-subtle)', paddingTop: 12,
            }}>
              {s.b}
            </div>
          )}
        </div>
      ))}
    </div>
  )
}

"""

if 'FwAccordion' not in src:
    src = src.replace(
        '// ── Page ─────────────────────────────────────────────────────',
        fw_component + '// ── Page ─────────────────────────────────────────────────────'
    )

src = src.replace(old_grid, new_grid)

with open(path, 'w') as f:
    f.write(src)
print('  ✓ Framework accordion added')
PYEOF

echo ""
echo "→ Running build..."
npm run build

if [ $? -eq 0 ]; then
  echo ""
  echo "✅ ALL CHANGES APPLIED"
  echo ""
  echo "Push live:"
  echo "  git add . && git commit -m 'feat: full audit fixes — risk labels, scarcity, accordion, sharper copy' && git push origin signal-mvp"
else
  echo ""
  echo "⚠ Build failed — paste errors here"
fi
