[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/case-studies/swiggy"
  to = "/case-studies/swiggy.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
